// Generated by drift_sounds_cli.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:drift_sounds/drift_sounds.dart' as _i1;
import 'package:flutter/material.dart' as _i2;

///Directory: sounds\ambiance.
class $SoundsAmbiance extends _i1.SoundDirectory {
  /// Create an instance.
  const $SoundsAmbiance({required this.db});

  /// The database where [sounds] are stored.
  @override
  final _i1.DriftSoundsDatabase db;

  /// sounds/ambiance/ambiance.mp3.
  _i1.DriftSoundReference get ambiance => _i1.DriftSoundReference(
    database: db,
    id: 1,
    name: 'sounds/ambiance/ambiance.mp3',
  );

  /// sounds/ambiance/intro.wav.
  _i1.DriftSoundReference get intro => _i1.DriftSoundReference(
    database: db,
    id: 2,
    name: 'sounds/ambiance/intro.wav',
  );

  /// The name of the directory where the [sounds] were loaded from.
  @override
  String get name => 'sounds/ambiance';

  /// The directories which appear below this one.
  @override
  List<_i1.SoundDirectory> get subdirectories => [];

  /// Return a list of all sound references.
  @override
  List<_i1.DriftSoundReference> get sounds => [ambiance, intro];
}

///Directory: sounds\doors.
class $SoundsDoors extends _i1.SoundDirectory {
  /// Create an instance.
  const $SoundsDoors({required this.db});

  /// The database where [sounds] are stored.
  @override
  final _i1.DriftSoundsDatabase db;

  /// sounds/doors/door_close_1.mp3.
  _i1.DriftSoundReference get doorClose1 => _i1.DriftSoundReference(
    database: db,
    id: 3,
    name: 'sounds/doors/door_close_1.mp3',
  );

  /// sounds/doors/door_close_2.mp3.
  _i1.DriftSoundReference get doorClose2 => _i1.DriftSoundReference(
    database: db,
    id: 4,
    name: 'sounds/doors/door_close_2.mp3',
  );

  /// sounds/doors/door_open_1.mp3.
  _i1.DriftSoundReference get doorOpen1 => _i1.DriftSoundReference(
    database: db,
    id: 5,
    name: 'sounds/doors/door_open_1.mp3',
  );

  /// sounds/doors/door_open_2.mp3.
  _i1.DriftSoundReference get doorOpen2 => _i1.DriftSoundReference(
    database: db,
    id: 6,
    name: 'sounds/doors/door_open_2.mp3',
  );

  /// The name of the directory where the [sounds] were loaded from.
  @override
  String get name => 'sounds/doors';

  /// The directories which appear below this one.
  @override
  List<_i1.SoundDirectory> get subdirectories => [];

  /// Return a list of all sound references.
  @override
  List<_i1.DriftSoundReference> get sounds => [
    doorClose1,
    doorClose2,
    doorOpen1,
    doorOpen2,
  ];
}

///Directory: sounds\footsteps\wooden_floor.
class $SoundsFootstepsWoodenFloor extends _i1.SoundDirectory {
  /// Create an instance.
  const $SoundsFootstepsWoodenFloor({required this.db});

  /// The database where [sounds] are stored.
  @override
  final _i1.DriftSoundsDatabase db;

  /// sounds/footsteps/wooden_floor/step_1.wav.
  _i1.DriftSoundReference get step1 => _i1.DriftSoundReference(
    database: db,
    id: 7,
    name: 'sounds/footsteps/wooden_floor/step_1.wav',
  );

  /// sounds/footsteps/wooden_floor/step_2.wav.
  _i1.DriftSoundReference get step2 => _i1.DriftSoundReference(
    database: db,
    id: 8,
    name: 'sounds/footsteps/wooden_floor/step_2.wav',
  );

  /// sounds/footsteps/wooden_floor/step_3.wav.
  _i1.DriftSoundReference get step3 => _i1.DriftSoundReference(
    database: db,
    id: 9,
    name: 'sounds/footsteps/wooden_floor/step_3.wav',
  );

  /// sounds/footsteps/wooden_floor/step_4.wav.
  _i1.DriftSoundReference get step4 => _i1.DriftSoundReference(
    database: db,
    id: 10,
    name: 'sounds/footsteps/wooden_floor/step_4.wav',
  );

  /// sounds/footsteps/wooden_floor/step_5.wav.
  _i1.DriftSoundReference get step5 => _i1.DriftSoundReference(
    database: db,
    id: 11,
    name: 'sounds/footsteps/wooden_floor/step_5.wav',
  );

  /// The name of the directory where the [sounds] were loaded from.
  @override
  String get name => 'sounds/footsteps/wooden_floor';

  /// The directories which appear below this one.
  @override
  List<_i1.SoundDirectory> get subdirectories => [];

  /// Return a list of all sound references.
  @override
  List<_i1.DriftSoundReference> get sounds => [
    step1,
    step2,
    step3,
    step4,
    step5,
  ];
}

///Directory: sounds\footsteps.
class $SoundsFootsteps extends _i1.SoundDirectory {
  /// Create an instance.
  const $SoundsFootsteps({required this.db});

  /// The database where [sounds] are stored.
  @override
  final _i1.DriftSoundsDatabase db;

  ///Directory: sounds\footsteps\wooden_floor.
  $SoundsFootstepsWoodenFloor get woodenFloor =>
      $SoundsFootstepsWoodenFloor(db: db);

  /// The name of the directory where the [sounds] were loaded from.
  @override
  String get name => 'sounds/footsteps';

  /// The directories which appear below this one.
  @override
  List<_i1.SoundDirectory> get subdirectories => [woodenFloor];

  /// Return a list of all sound references.
  @override
  List<_i1.DriftSoundReference> get sounds => [];
}

/// A class representing sounds in a directory.
///
/// This class was generated by [drift_sounds_cli](https://github.com/chrisnorman7/drift_sounds_cli).
///
/// Directory: sounds.
class Sounds extends _i1.SoundDirectory {
  /// Create an instance.
  const Sounds({required this.db});

  /// The database to use.
  @override
  final _i1.DriftSoundsDatabase db;

  ///Directory: sounds\ambiance.
  $SoundsAmbiance get ambiance => $SoundsAmbiance(db: db);

  ///Directory: sounds\doors.
  $SoundsDoors get doors => $SoundsDoors(db: db);

  ///Directory: sounds\footsteps\wooden_floor.
  $SoundsFootstepsWoodenFloor get woodenFloor =>
      $SoundsFootstepsWoodenFloor(db: db);

  ///Directory: sounds\footsteps.
  $SoundsFootsteps get footsteps => $SoundsFootsteps(db: db);

  /// The name of the directory where the [sounds] were loaded from.
  @override
  String get name => 'sounds';

  /// The directories which appear below this one.
  @override
  List<_i1.SoundDirectory> get subdirectories => [
    ambiance,
    doors,
    woodenFloor,
    footsteps,
  ];

  /// Return a list of all sound references.
  @override
  List<_i1.DriftSoundReference> get sounds => [];
}

/// Provide the [sounds] getter.
extension BuildContextSoundsX on _i2.BuildContext {
  //// Returns the loaded sounds.
  Sounds get sounds {
    final db = _i1.DriftSoundsDatabaseProvider.of(this);
    return Sounds(db: db);
  }
}
